[package]
name = "FileFlow"
version = "1.0.0"
description = "An app to insert CSV data into a database"
authors = ["Maxime-Cllt"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "1", features = [] }

[dependencies]
tauri = { version = "1", features = ["api-all"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sqlx = { version = "0.8.2", features = ["runtime-tokio-native-tls", "mysql", "postgres", "sqlite"] }
tokio = { version = "1", features = ["full"] }
postgres = "^0.19"
csv = "1.3.0"

[features]
# This feature is used for production builds or when a dev server is not specified, DO NOT REMOVE!!
custom-protocol = ["tauri/custom-protocol"]

[profile.dev]
incremental = true # Compile your binary in smaller steps.
codegen-units = 1
opt-level = 0 # Prioritizes fast compilation.
panic = "unwind" # Allows for better debugging.
debug = true # Enables debug symbols.


[profile.release]
codegen-units = 1 # Allows LLVM to perform better optimization.
opt-level = 2 # Prioritizes small binary size. Use `3` if you prefer speed.
panic = "abort" # Higher performance by disabling panic handlers.
strip = true # Ensures debug symbols are removed.

