name: Rust CI

on:
  push:
    branches: [ "v1.0.1" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Fetch Repository
        uses: actions/checkout@v4

      - name: Install stable Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          target: x86_64-unknown-linux-gnu

      - name: Run tests
        run: |
          cd src-tauri
          cargo test --verbose