name: Rust CI

on:
  push:
    branches: [ "v1.0.1" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Move to src-tauri
        run: cd src-tauri

      - name: Run tests
        run: cargo test --verbose